global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#viktor_lomtev'

