
version: '3.3'
services:
  post_db:
    #container_name: sobones-mongodb-container
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      - back_net
  ui:
    #container_name: sobones-ui-container
    #build: ../src/ui
    image: ${USERNAME}/ui:${UI_SERVICE_VERSION}
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
      - POST_SERVICE_HOST=post
      - POST_SERVICE_PORT=5000
      - COMMENT_SERVICE_HOST=comment
      - COMMENT_SERVICE_PORT=9292
    ports:
      - ${UI}:9292/tcp
    networks:
      - front_net
    depends_on:
      - post
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.ui
#  post:
    #container_name: sobones-post-container
    #build: ../src/post-py
 #   image: ${USERNAME}/post:${POST_SERVICE_VERSION}
  #  networks:
   #   - front_net
    #  - back_net
  post:
    image: ${USER_NAME}/post:${POST_SERVICE_VERSION}
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
      - POST_DATABASE_HOST=post_db
      - POST_DATABASE=posts
    depends_on:
      - post_db
    ports:
      - "5000:5000"
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.post
    networks:
      - front_net
      - back_net


  comment:
    #container_name: sobones-comment-container
    #build: ../src/comment
    image: ${USERNAME}/comment:${COMMENT_SERVICE_VERSION}
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}

    networks:
      - front_net
      - back_net
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.post

volumes:
  post_db:

networks:
  front_net:
  back_net:

