{
 "title": "UI service monitoring",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Histogram",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(ui_request_latency_second_bucket[5m])) by (le))"
    }
   ]
  },
  {
   "title": "Ui http request",
   "type": "graph",
   "description": "All http requests than ui service reiceives",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "uui_request_count" }
   ]
  },
  {
   "title": "UI http request with status code",
   "type": "graph",
   "description": "All http",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ]
  }
 ]
}